In [49]:
import math
import numpy as np

In [ ]:
theta = float(input("Opening angle (rad)"))
m_a = float(input("Initial Mass"))
m_1 = float(input("Mass 1"))
m_2 = float(input("Mass 2"))
k_a = float(input("A momentum")) #initial momentum in lab frame

In [45]:
P_mag = (math.sqrt((m_a**4) + (m_1**4) + (m_2**4)
                   - 2*(m_a**2)*(m_1**2) - 2*(m_a**2)*(m_2**2) - 2*(m_1**2)*(m_2**2)) 
                   / (2*m_a))                  #3 momentum magnitude of daughter particles in A frame
E_1 = (m_a**2 + m_1**2 - m_2**2)/(2*m_a)      #energy of daughter particles in A frame
E_2 = (m_a**2 + m_2**2 - m_1**2)/(2*m_a)

E_a = math.sqrt(m_a**2 + k_a**2)            # energy of A in lab frame
gamma = E_a / m_a
beta = math.sqrt(1 - (1/gamma)**2)

P1_4 = np.array([[E_1], [P_mag*np.cos(theta)], [P_mag*np.sin(theta)]])     #four momenta in A frame
P2_4 = np.array([[E_2], [-P_mag*np.cos(theta)], [-P_mag*np.sin(theta)]])

boost = np.array([[gamma, -beta*gamma, 0],    # A to Lab frame boost
                  [-beta*gamma, gamma, 0], 
                  [0, 0, 1]])



In [47]:
print(P1_4_lab)
print(P2_4_lab)

[[0.61611061]
 [0.9973348 ]
 [2.21636173]]
[[ 1.61995737]
 [-1.9973348 ]
 [-2.21636173]]


In [97]:
def get_boost_2(m, p):     # from m-rest frame to m-p frame
    E = math.sqrt(m**2 + p**2)
    gamma = E / m
    beta = math.sqrt(1 - (1/gamma)**2)

    boost = np.array([[gamma, -beta*gamma, 0, 0], 
                      [-beta*gamma, gamma, 0, 0], 
                      [0, 0, 1, 0], 
                      [0, 0, 0, 1]])
    return boost


def get_boost_1(m_a, m_1, m_2):     # from m-rest frame to m-p frame
    p = (math.sqrt(((m_a**4) + (m_1**4) + (m_2**4)
                   - 2*(m_a**2)*(m_1**2) - 2*(m_a**2)*(m_2**2) - 2*(m_1**2)*(m_2**2)))
                   / (2*m_a))
    E = math.sqrt(m_a**2 + p**2)
    gamma = E / m_a
    beta = math.sqrt(1 - (1/gamma)**2)

    boost = np.array([[gamma, -beta*gamma, 0, 0], #boost matrix aligned with x-axis
                      [-beta*gamma, gamma, 0, 0], 
                      [0, 0, 1, 0], 
                      [0, 0, 0, 1]])
    return boost

def get_4_momentum(m_a, m_1, m_2, theta, phi):
    p = (math.sqrt((m_a**4) + (m_1**4) + (m_2**4)
                   - 2*(m_a**2)*(m_1**2) - 2*(m_a**2)*(m_2**2) - 2*(m_1**2)*(m_2**2)) 
                    / (2*m_a))
    E_1 = (m_a**2 + m_1**2 - m_2**2)/(2*m_a)      #energy of daughter particles in A frame
    E_2 = (m_a**2 + m_2**2 - m_1**2)/(2*m_a)

    P1 = np.array([[E_1], [p*np.cos(theta)],  [p*np.sin(theta)*np.cos(phi)],  [p*np.sin(theta)*np.sin(phi)]])     #four momenta in A frame
    P2 = np.array([[E_2], [-p*np.cos(theta)], [-p*np.sin(theta)*np.cos(phi)], [-p*np.sin(theta)*np.sin(phi)]])

    return P1, P2

In [77]:
m_alpha = float(input("Initial mass: "))
m_a = float(input("Intermediate mass: "))
m_b = m_a
m_1 = float(input("Final mass: "))
m_2 = m_1
m_3 = m_1
m_4 = m_1

theta_1 = float(input("Opening angle 1 (0-pi): "))     #between the momentum of particle 1 in particle a's rest frame to the boost axis of particle a in alpha's rest frame
phi_1 = float(input("Opening angle rotation 0-2pi: ")) #rotation around the boost axis
theta_2 = float(input("Opening angle 2 (0-pi): "))     #between the momentum of particle 1 in particle a's rest frame to the boost axis of particle a in alpha's rest frame
phi_2 = float(input("Opening angle rotation 0-2pi: "))
psi = float(input("Opening angle a: "))

l = float(input("Initial momentum: "))



Initial mass:  8
Intermediate mass:  3
Final mass:  1
Opening angle 1 (0-pi):  0
Opening angle rotation 0-2pi:  0
Opening angle 2 (0-pi):  0
Opening angle rotation 0-2pi:  0
Opening angle a:  0
Initial momentum:  3


In [107]:
p1_4, p2_4 = get_4_momentum(m_a, m_1, m_2, theta_1, phi_1)
p3_4, p4_4 = get_4_momentum(m_b, m_3, m_4, theta_2, phi_2)

boost1 = get_boost_1(m_alpha, m_a, m_b)

R = np.array([[1,  0,           0,           0],     #rotation into boost 2 axis
              [0,  np.cos(psi), np.sin(psi), 0],
              [0, -np.sin(psi), np.cos(psi), 0],
              [0,  0,           0,            1]])
R2 = np.array([[1,  0,           0,           0],     #rotation into boost 2 axis
              [0,  np.cos(math.pi-psi), np.sin(math.pi-psi), 0],
              [0, -np.sin(math.pi-psi), np.cos(math.pi-psi), 0],
              [0,  0,           0,            1]])

boost2 = get_boost_2(m_alpha, l)

P1_final = np.matmul(boost2, np.matmul(R, np.matmul(boost1, p1_4)))    # boost2 * R(psi) * boost1 * P1_4 = P1_4 in lab frame
P2_final = np.matmul(boost2, np.matmul(R, np.matmul(boost1, p2_4))) 
P3_final = np.matmul(boost2, np.matmul(R2, np.matmul(boost1, p3_4))) 
P4_final = np.matmul(boost2, np.matmul(R2, np.matmul(boost1, p4_4))) 

In [109]:
print(P1_final)
print(P2_final)
print(P3_final)
print(P4_final)

[[1.03687179]
 [0.27404945]
 [0.        ]
 [0.        ]]
[[ 2.70986146]
 [-2.51860063]
 [ 0.        ]
 [ 0.        ]]
[[ 1.54800568e+00]
 [-1.18166052e+00]
 [-8.34611317e-17]
 [ 0.00000000e+00]]
[[1.45461001e+00]
 [1.05635707e+00]
 [2.04965289e-16]
 [0.00000000e+00]]
