In [1]:
import math
import numpy as np

In [3]:
theta = 1
m_a = 3
m_1 = 1
m_2 = m_1
k_a = 2 #initial momentum in lab frame

In [5]:
P_mag = (math.sqrt((m_a**4) + (m_1**4) + (m_2**4)
                   - 2*(m_a**2)*(m_1**2) - 2*(m_a**2)*(m_2**2) - 2*(m_1**2)*(m_2**2)) 
                   / (2*m_a))                  #3 momentum magnitude of daughter particles in A frame
E_1 = (m_a**2 + m_1**2 - m_2**2)/(2*m_a)      #energy of daughter particles in A frame
E_2 = (m_a**2 + m_2**2 - m_1**2)/(2*m_a)

E_a = math.sqrt(m_a**2 + k_a**2)            # energy of A in lab frame
gamma = E_a / m_a
beta = math.sqrt(1 - (1/gamma)**2)

P1_4 = np.array([[E_1], [P_mag*np.cos(theta)], [P_mag*np.sin(theta)]])     #four momenta in A frame
P2_4 = np.array([[E_2], [-P_mag*np.cos(theta)], [-P_mag*np.sin(theta)]])

boost = np.array([[gamma, -beta*gamma, 0],    # A to Lab frame boost
                  [-beta*gamma, gamma, 0], 
                  [0, 0, 1]])

P1_4_lab = np.matmul(boost, P1_4)
P2_4_lab = np.matmul(boost, P2_4)

In [7]:
print(P1_4_lab)
print(P2_4_lab)

[[ 1.40005808]
 [-0.27399059]
 [ 0.94079316]]
[[ 2.2054932 ]
 [-1.72600941]
 [-0.94079316]]


In [79]:
def get_boost_2(m, p):     # from m-rest frame to m-p frame
    E = math.sqrt(m**2 + p**2)
    gamma = E / m
    beta = math.sqrt(1 - (1/gamma)**2)

    boost = np.array([[gamma, -beta*gamma, 0, 0], 
                      [-beta*gamma, gamma, 0, 0], 
                      [0, 0, 1, 0], 
                      [0, 0, 0, 1]])
    return boost


def get_boost_1(m_a, m_1, m_2):     # from m-rest frame to m-p frame
    p = (math.sqrt(((m_a**4) + (m_1**4) + (m_2**4)
                   - 2*(m_a**2)*(m_1**2) - 2*(m_a**2)*(m_2**2) - 2*(m_1**2)*(m_2**2)))
                   / (2*m_a))
    E = math.sqrt(m_1**2 + p**2)  
    gamma = E / m_1
    beta = math.sqrt(1 - (1/gamma)**2)

    boost = np.array([[gamma, -beta*gamma, 0, 0], #boost matrix aligned with x-axis
                      [-beta*gamma, gamma, 0, 0], 
                      [0, 0, 1, 0], 
                      [0, 0, 0, 1]])
    return boost

def get_4_momentum(m_a, m_1, m_2, theta, phi):
    p = (math.sqrt((m_a**4) + (m_1**4) + (m_2**4)
                   - 2*(m_a**2)*(m_1**2) - 2*(m_a**2)*(m_2**2) - 2*(m_1**2)*(m_2**2)) 
                    / (2*m_a))
    E_1 = (m_a**2 + m_1**2 - m_2**2)/(2*m_a)      #energy of daughter particles in A frame
    E_2 = (m_a**2 + m_2**2 - m_1**2)/(2*m_a)

    P1 = np.array([[E_1], [p*np.cos(theta)],  [p*np.sin(theta)*np.cos(phi)],  [p*np.sin(theta)*np.sin(phi)]])     #four momenta in A frame
    P2 = np.array([[E_2], [-p*np.cos(theta)], [-p*np.sin(theta)*np.cos(phi)], [-p*np.sin(theta)*np.sin(phi)]])

    return P1, P2

In [81]:
m_alpha = 8
m_a = 3
m_b = m_a
m_1 = 1
m_2 = m_1
m_3 = m_1
m_4 = m_1

theta_1 = 0     #between the momentum of particle 1 in particle a's rest frame to the boost axis of particle a in alpha's rest frame
phi_1   = 0     #rotation around the boost axis
theta_2 = 1     #between the momentum of particle 1 in particle a's rest frame to the boost axis of particle a in alpha's rest frame
phi_2   = 0
psi     = 0

l = 3

In [83]:
p1_4, p2_4 = get_4_momentum(m_a, m_1, m_2, theta_1, phi_1)
p3_4, p4_4 = get_4_momentum(m_b, m_3, m_4, theta_2, phi_2)

boost1 = get_boost_1(m_alpha, m_a, m_b)

R = np.array([[1,  0,           0,           0],     #rotation into boost 2 axis
              [0,  np.cos(psi), np.sin(psi), 0],
              [0, -np.sin(psi), np.cos(psi), 0],
              [0,  0,           0,            1]])
R2 = np.array([[1,  0,           0,           0],     #rotation into boost 2 axis
              [0,  np.cos(math.pi-psi), np.sin(math.pi-psi), 0],
              [0, -np.sin(math.pi-psi), np.cos(math.pi-psi), 0],
              [0,  0,           0,            1]])

boost2 = get_boost_2(m_alpha, l)

P1_final = np.matmul(boost2, np.matmul(R,  np.matmul(boost1, p1_4)))    # boost2 * R(psi) * boost1 * P1_4 = P1_4 in lab frame
P2_final = np.matmul(boost2, np.matmul(R,  np.matmul(boost1, p2_4))) 
P3_final = np.matmul(boost2, np.matmul(R2, np.matmul(boost1, p3_4))) 
P4_final = np.matmul(boost2, np.matmul(R2, np.matmul(boost1, p4_4))) 

In [85]:
print(P1_final)
print(P2_final)
print(P3_final)
print(P4_final)

[[ 1.01999965]
 [-0.20099574]
 [ 0.        ]
 [ 0.        ]]
[[ 4.24415896]
 [-4.1246679 ]
 [ 0.        ]
 [ 0.        ]]
[[ 1.37298855]
 [ 0.0024062 ]
 [-0.94079316]
 [ 0.        ]]
[[1.90685658]
 [1.32325744]
 [0.94079316]
 [0.        ]]


In [31]:
print(p1_4)
print(p2_4)

[[1.5       ]
 [1.11803399]
 [0.        ]
 [0.        ]]
[[ 1.5       ]
 [-1.11803399]
 [-0.        ]
 [-0.        ]]


In [75]:
from scipy.integrate import quad
from scipy.integrate import simpson

In [73]:
def intg(psi):
    p = np.array([[1],[2],[3],[4]])
    R = np.array([[1,  0,           0,           0], 
                  [0,  np.cos(psi), np.sin(psi), 0],
                  [0, -np.sin(psi), np.cos(psi), 0],
                  [0,  0,           0,           1]])
    P = np.matmul(R,  p)
    return P


In [77]:

a = quad(intg, 0, np.pi)

C:\Users\banna\AppData\Local\Temp\ipykernel_24540\1439531938.py:2: DeprecationWarning: You are passing x=[0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1] as a positional argument. Please change your invocation to use keyword arguments. From SciPy 1.14, passing these as positional arguments will result in an error.
  a = simpson(intg, x)


IndexError: tuple index out of range

[[1]
 [2]
 [3]
 [4]]


In [59]:
print(intg(1))

[[ 1.        ]
 [ 3.60501757]
 [-0.06203505]
 [ 4.        ]]
